# 2 Spicy
2spicy: # Name used for the .game file
  display_name: "2 Spicy" # Name Display for the script
  launcher_path: "elf" # path for the game exec
  steps: # Steps to perform
    - file: "2spicy.bin"
      filesystem: "ext2" # File system to use for the mount (ext2 by default)
      copy_dirs:
        - "disk0"

# After Burner Climax (SDX)
abclisdx:
  display_name: "After Burner Climax (SDX)"
  launcher_path: ""
  steps:
    - file: "abc.bin"
      copy_dirs:
        - "disk0"
        - "disk1"

# Ghost Squad Evolution
ghostsev:
  display_name: "Ghost Squad Evolution"
  launcher_path: "vsg_l"
  steps:
    - file: "gsevo.bin"
      copy_dirs:
        - "disk0"
        - "disk1"
      remove_dirs:
        - "drv"

# Harley Davidson King of the Road
hdkotr:
  display_name: "Harley Davidson King of the Road"
  launcher_path: "elf"
  steps:
    - file: "harley.bin"
      copy_dirs:
        - "disk0"
      remove_dirs:
        - "drv"
    - file: "harley_fs.bin"
      copy_dirs: []
      destination_subfolder: "fs"
    - file: "harley_fs2.bin"
      copy_dirs: []
      destination_subfolder: "fs"

# The House of the Dead 4 (Rev A)
hotd4a:
  display_name: "The House of the Dead 4 (Rev A)"
  launcher_path: "elf"
  steps:
    - file: "hotd4.bin"
      copy_dirs:
        - "disk0"

# The House of the Dead 4 Special (NO GOOD DUMP FOUND)
#hotd4sp:
#  display_name: "The House of the Dead 4 Special"
#  launcher_path: "elf"
#  steps:
#    - file: "hotd4sp.bin"
#      copy_dirs:
#        - "disk0"
#      remove_dirs:
#        - "drv"

# The House of the Dead EX
hotdex:
  display_name: "The House of the Dead EX (Japan)"
  launcher_path: "elf"
  steps:
    - file: "hotdex.bin"
      copy_dirs:
        - "disk0"
      remove_dirs:
        - "drv"

# Hummer Extreme Edition
hummerxt:
  display_name: "Hummer Extreme Edition"
  launcher_path: ""
  steps:
    - file: "hummer.bin"
      copy_dirs:
        - "disk0"
      remove_dirs:
        - "drv"

# Hummer SDLX (NO GOOD DUMP FOUND)
#hummer:
#  display_name: "Hummer SDLX"
#  launcher_path: ""
#  steps:
#    - file: "hummer.bin"
#      copy_dirs:
#        - "disk0"
#      remove_dirs:
#        - "drv"

# Initial D Arcade Stage 4 (Rev B)
initiad4b:
  display_name: "Initial D Arcade Stage 4 (Rev B)"
  launcher_path: ""
  steps:
    - file: "id4.bin"
      copy_dirs:
        - "disk0"

# Initial D 4 (Export) (Rev D)
initiad4ex:
  display_name: "Initial D 4 (Export) (Rev D)"
  launcher_path: ""
  steps:
    - file: "id4exp.bin"
      copy_dirs:
        - "disk0"

# Initial D 5 (Export) (2.0)
initiad5exa:
  display_name: "Initial D 5 (Export) (2.0)"
  launcher_path: ""
  steps:
    - file: "initiald5.bin"
      filesystem: "ext3"
      copy_dirs:
        - "disk0"
    - file: "id5_data.bin"
      filesystem: "ext3"
      copy_dirs: []
      destination_subfolder: "data"
      remove_dirs:
        - "drv"
# Let's Go Jungle
letsgoju:
  display_name: "Let's Go Jungle"
  launcher_path: ""
  steps:
    - file: "lgj.bin"
      copy_dirs:
        - "disk0"

# Outrun 2 SP SDX Rev A
outr2sdx:
  display_name: "Outrun 2 SP SDX (Rev A)"
  launcher_path: "Jennifer"
  steps:
    - file: "or2.bin"
      copy_dirs:
        - "disk0"
      remove_dirs:
        - "drv"

# Outrun 2 SP SDX (Bootleg)
outr2sdxg:
  display_name: "Outrun 2 SP SDX (Bootleg)"
  launcher_path: "Jennifer"
  steps:
    - file: "or2g.bin"
      copy_dirs:
        - "disk0"
      remove_dirs:
        - "drv"

# Primeval Hunt
primevah:
  display_name: "Primeval Hunt"
  launcher_path: "prog"
  steps:
    - file: "primevil.bin"
      copy_dirs:
        - "disk0"
      remove_dirs:
        - "drv"

# R-Tuned: Ultimate Street Racing
rtuned:
  display_name: "R-Tuned: Ultimate Street Racing"
  launcher_path: ""
  steps:
    - file: "rtuned.bin"
      copy_dirs:
        - "disk0"
      remove_dirs:
        - "drv"
        - "drv.old"

# Rambo (Export)
rambo:
  display_name: "Rambo (Export)"
  launcher_path: "elf"
  steps:
    - file: "rambo.bin"
      copy_dirs:
        - "disk0"

# Sega Race-TV (Export)
segartv:
  display_name: "Sega Race-TV (Export)"
  launcher_path: ""
  steps:
    - file: "segartv.bin"
      copy_dirs:
        - "disk0"
      remove_dirs:
        - "drv"

# Virtua Fighter 5
vf5:
  display_name: "Virtua Fighter 5"
  launcher_path: ""
  steps:
    - file: "vf5.bin"
      copy_dirs:
        - "disk0"
        - "disk1"

# Virtua Fighter 5 (Rev E)(ver C)
vf5e:
  display_name: "Virtua Fighter 5 (Rev E)(ver C)"
  launcher_path: ""
  steps:
    - file: "vf5c.bin"
      copy_dirs:
        - "disk0"
        - "disk1"
      remove_dirs:
        - "drv"
    - file: "vf5c_rom.bin"
      copy_dirs: []
      destination_subfolder: "rom"

# Virtua Fighter 5 Final Showdown (Rev A, v2.0)
vf5fsa2:
  display_name: "Virtua Fighter 5 Final Showdown (Rev A, v2.0)"
  launcher_path: ""
  steps:
    - file: "vf5fs.bin"
      copy_dirs:
        - "disk0"
        - "disk1"
      remove_dirs:
        - "drv"
    - file: "vf5fs_ext.bin"
      extra_copy_dirs:
        - source: "rom"
          destination: "rom"

# Virtua Fighter 5 R (Rev G)
vf5r:
  display_name: "Virtua Fighter 5 R (Rev G)"
  launcher_path: ""
  steps:
    - file: "vf5r.bin"
      copy_dirs:
        - "disk0"
      remove_dirs:
        - "drv"
    - file: "vf5r_rom.bin"
      copy_dirs: []
      destination_subfolder: "rom"
  final_move:
    - source: "ext/rom/objset"
      destination: "rom/objset"

# Virtua Tennis 3
# psmash3:
# display_name: "Virtua Tennis 3 (Rev C)"
# launcher_path: "vt3_Lindbergh"
# filesystem: "ext2"
# steps:
#  - file: "vt3.bin"
#    copy_dirs:
#      - "disk0"
